// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApg1kwmobKOObi32kB5RBSiJkOEaTgq4',
    appId: '1:1076012274723:android:0c1c278bb8d5a152ff0d96',
    messagingSenderId: '1076012274723',
    projectId: 'foodly-99135',
    storageBucket: 'foodly-99135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYXvT3lDN6nqquCJ4G6CnaCM5x-d7Hzo',
    appId: '1:1076012274723:ios:48a404258909d55fff0d96',
    messagingSenderId: '1076012274723',
    projectId: 'foodly-99135',
    storageBucket: 'foodly-99135.firebasestorage.app',
    iosBundleId: 'io.devmahnx.ordereats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVKvhmhIbkBIkgVzEXPhTq6iFr7DVlmgw',
    appId: '1:1076012274723:web:03889313d519065aff0d96',
    messagingSenderId: '1076012274723',
    projectId: 'foodly-99135',
    authDomain: 'foodly-99135.firebaseapp.com',
    storageBucket: 'foodly-99135.firebasestorage.app',
    measurementId: 'G-G97VCN558J',
  );
}
